# Generated by Django 5.1.1 on 2024-10-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amout', models.FloatField(default=0)),
                ('budget_period_in_days', models.IntegerField(default=0)),
                ('account_currency', models.CharField(default='USD', max_length=50)),
            ],
        ),
    ]
