# Generated by Django 5.1.1 on 2024-10-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_prefs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefs',
            old_name='budget_amout',
            new_name='budget_amount',
        ),
    ]
